version: "3.9"
services:
  web:
    image: joelwembo/django-app-ecr-repo
    container_name: django-app-ecr-repo
    env_file: .env
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - /bin/sh
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000 
    ports:
      - "8000:8000"
    networks:
      - web_network
    volumes:
       - appdata:/app
  
networks:
  web_network:
    driver: bridge

volumes:
  appdata:
   driver: local

  